<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="irb120" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  #<xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  #<xacro:property name="height1" value="2" /> <!-- Link 1 -->
  #<xacro:property name="height2" value="1" /> <!-- Link 2 -->
  #<xacro:property name="height3" value="1" /> <!-- Link 3 -->
  #<xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  #<xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find irb120_description)/urdf/irb120.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find irb120_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- also, define a flange frame consistent w/ DH and IK library; z-axis pointing out from flange -->  
    <link name="flange_frame"/>

  <joint name="flange_frame_jnt" type="fixed">
    <parent link="link7"/>
    <child link="flange_frame"/>
    <origin xyz="0 0 0" rpy="0 1.5708 0"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision-->

    <!--visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://irb120_description/meshes/irb120/visual/base_link.stl"/>
      </geometry>
      <material name="abb_orange">
        <color rgba="1 0.43 0 1"/>
      </material>      
    </visua-->

    <visual>
      <!--origin xyz="0 0 ${height1/2}" rpy="0 0 0"/-->
       <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height1}"/-->
	       <mesh filename="package://irb120_description/meshes/irb120/visual/base_link.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <limit effort="100" lower="-2.87979" upper="2.87979" velocity="4.36332"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height2}"/-->
	<mesh filename="package://irb120_description/meshes/irb120/collision/link_1.stl"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin rpy="0 0 0" xyz="0 0 0.29"/>
    <axis xyz="0 1 0"/>
    <limit effort="500" lower="-1.91986" upper="1.91986" velocity="4.36332"/>    
    <dynamics damping="1.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	<mesh filename="package://irb120_description/meshes/irb120/visual/link_2.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 -0.2" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <link name="link4">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.2 0.2"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_3.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint3" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin rpy="0 0 0" xyz="0 0 0.27"/>
    <axis xyz="0 1 0"/>
   <limit effort="100" lower="-1.91986" upper="1.22173" velocity="4.36332"/>    
    <dynamics damping="1.7"/>
  </joint>  
 
   <link name="link5">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_4.stl"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_4.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint4" type="continuous">
    <parent link="link4"/>
    <child link="link5"/>
    <origin rpy="0 0 0" xyz="0 0 0.07"/>
    <axis xyz="1 0 0"/>
    <limit effort="20" lower="-2.79253" upper="2.79253" velocity="5.58505"/>    
    <dynamics damping="1.7"/>
  </joint>  
   
   <link name="link6">
    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_5.stl"/>
      </geometry>
    </collision-->

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_5.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint5" type="continuous">
    <parent link="link5"/>
    <child link="link6"/>
   <origin rpy="0 0 0" xyz="0.302 0 0"/>
    <axis xyz="0 1 0"/>
     <limit effort="20" lower="-2.094395" upper="2.094395" velocity="5.58505"/>   
    <dynamics damping="1.7"/>
  </joint> 

   <link name="link7">
    <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_6.stl"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<!--box size="${width} ${width} ${height3}"/-->
	        <mesh filename="package://irb120_description/meshes/irb120/visual/link_6.stl"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="joint6" type="continuous">
    <parent link="link6"/>
    <child link="link7"/>
    <origin rpy="0 0 0" xyz="0.072 0 0"/>
    <axis xyz="1 0 0"/>
     <limit effort="20" lower="-6.98132" upper="6.98132" velocity="7.33038"/>   
    <dynamics damping="0.7"/>
  </joint> 
    

 
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>flange_stf
[ INFO] [1512929221.358296873, 54.845000000]: frame_id: system_ref_frame

[ INFO] [1512929221.358314256, 54.845000000]: child_frame_id: link7

    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> 
 
</robot>
